version: '3'

# START FIRST GROUP TO DISPLAY PDC
services:
   vnc:
     image: vnc
     container_name: vnc
     networks:      
      net:
         ipv4_address: 172.33.0.2
   
   sockify:
     image: sockify
     container_name: sockify
     network_mode: service:vnc
   
   tiger:
     image: tiger
     container_name: tiger
     network_mode: service:vnc
     volumes:
      - sharedVolumePDC:/tmp
     
   
# START SECOND GROUP TO DISPLAY PMU1
   vnc1:
     image: vnc
     container_name: vnc1
     networks:      
      net1:
         ipv4_address: 172.30.0.2
   
   sockify1:
     image: sockify
     container_name: sockify1
     network_mode: service:vnc1
   
   tiger1:
     image: tiger
     container_name: tiger1
     network_mode: service:vnc1
     volumes:
      - sharedVolumePMU1:/tmp

# START THIRD GROUP TO DISPLAY PMU2
   vnc2:
     image: vnc
     container_name: vnc2
     networks:      
      net2:
         ipv4_address: 172.31.0.2
   
   sockify2:
     image: sockify
     container_name: sockify2
     network_mode: service:vnc2
   
   tiger2:
     image: tiger
     container_name: tiger2
     network_mode: service:vnc2
     volumes:
      - sharedVolumePMU2:/tmp

# START THIRD GROUP TO DISPLAY PMU3
   vnc3:
     image: vnc
     container_name: vnc3
     networks:      
      net3:
         ipv4_address: 172.32.0.2
   
   sockify3:
     image: sockify
     container_name: sockify3
     network_mode: service:vnc3
   
   tiger3:
     image: tiger
     container_name: tiger3
     network_mode: service:vnc3
     volumes:
      - sharedVolumePMU3:/tmp

# START FIFTH GROUP TO DISPLAY PDC_H
   vnc4:
     image: vnc
     container_name: vnc4
     networks:      
      net4:
         ipv4_address: 172.34.0.2
   
   sockify4:
     image: sockify
     container_name: sockify4
     network_mode: service:vnc4
   
   tiger4:
     image: tiger
     container_name: tiger4
     network_mode: service:vnc4
     volumes:
      - sharedVolumePDC_H:/tmp
 

   mysql:
     image: mysql
     container_name: mysql
     networks:
       pdc_net:                
         ipv4_address: 172.23.0.2
     environment:
      - MYSQL_ROOT_PASSWORD=rootpass
     volumes:
      - /home/testing/Desktop/old_deploy/services/scripts:/docker-entrypoint-initdb.d:ro
      - /home/testing/Desktop/old_deploy/services/database:/var/lib/mysql
     expose:
      - 3306


   mysqlH:
     image: mysql
     container_name: mysqlH
     networks:
       pdcH_net:                
         ipv4_address: 172.24.0.2
     environment:
      - MYSQL_ROOT_PASSWORD=rootpass
     volumes:
      - /home/testing/Desktop/old_deploy/services/scripts:/docker-entrypoint-initdb.d:ro
      - /home/testing/Desktop/old_deploy/services/databaseH:/var/lib/mysqlw
     expose:
      - 3306


 

networks:    
   net:
     ipam:  
       config:      
          - subnet: 172.33.0.0/16  #USED TO DISPLAY PDC
   net1:
     ipam:  
       config:      
          - subnet: 172.30.0.0/16  #USED TO DISPLAY PMU1
   net2:
     ipam:  
       config:      
          - subnet: 172.31.0.0/16  #USED TO DISPLAY PMU2
   net3:
     ipam:  
       config:      
          - subnet: 172.32.0.0/16  #USED TO DISPLAY PMU3
   net4:
     ipam:  
       config:     
          - subnet: 172.34.0.0/16  #USED TO DISPLAY PDC_H
   pdcH_net:
     ipam:  
       config:      
          - subnet: 172.24.0.0/16  #PDC_H NETWORK
   pdc_net:
     ipam:  
       config:      
          - subnet: 172.23.0.0/16  #PDC NETWORK

   

volumes:
  sharedVolumePDC: {}
  sharedVolumePDC_H: {}
  sharedVolumePMU1: {}
  sharedVolumePMU2: {}
  sharedVolumePMU3: {}

