FROM ubuntu:18.04


# Prevent apt from prompting the user for input during install/configuration
ENV DEBIAN_FRONTEND=noninteractive

#Install required libraries
RUN apt-get update && \
    apt-get install -y libmysqlclient-dev && \
    apt-get install -y wget && \
    apt-get install -y build-essential

#download iPDC, upack it and install DB executable
RUN  mkdir -p /tool/iPDC && \    
     wget  https://sourceforge.net/projects/iitbpdc/files/iPDC-v1.3.1.tar.gz -P /tool/iPDC  && \
     tar -xvf /tool/iPDC/iPDC-v1.3.1.tar.gz -C /tool/iPDC && \
     rm /tool/iPDC/*.gz && \
     cd /tool/iPDC/iPDC-v1.3.1/DBServer-1.1 && \
     sed -i -e 's/storage_engine/default_storage_engine/g' Db.sql && \
     sed -i -e 's/password = "root"/password = "rootpass"/g' connections.c && \
     sed -i -e 's/server = "localhost"/server = "mysql"/g' connections.c && \
     sed -i -e 's/user = "root"/user = "root"/g' connections.c && \
     chmod 777 -R /tool  && \
     make install .



EXPOSE 9000/udp


# CMD [ "executable", "parameter", ... ] form throws an error # Therefore, bash-like form is used
ENTRYPOINT   /tool/iPDC/iPDC-v1.3.1/DBServer-1.1/./DBServer


